config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/notfound", to: "users#notfound"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: :edit
  resources :password_resets, except: [:index, :show, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t(".foot_message",
      link_to_tutorial: link_to(t("static_pages.help.tutorial_message"),
      "https://www.railstutorial.org/"),
      link_to_micheal: link_to(t(".michael"),
      "http://www.michaelhartl.com/")).html_safe %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("static_pages.about.title_message"), about_path %></li>
      <li><%= link_to t("static_pages.contact.title_message"), contact_path %></li>
      <li><%= link_to t(".new"), "http://news.railstutorial.org/" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".home_message"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("static_pages.home.title_message"), root_path %></li>
        <li><%= link_to t("static_pages.help.title_message"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t(".user_title"), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t ".account" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".setting"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li> <%= link_to t(".logout"), logout_path, method: :delete %> </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".login_message"), login_path %></li>
        <% end %>
        <li><%= link_to "EN", help_path %></li>
        <li><%= link_to "VI", help_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= full_title yield(:title) %> </title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
    <%= javascript_include_tag "i18n" %>
    <%= javascript_include_tag "translations", skip_pipeline: true %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>